from enum import Enum


class Province(Enum):
    ALAVA = "alava"
    ALBACETE = "albacete"
    ALICANTE = "alicante"
    ALMERIA = "almeria"
    ASTURIAS = "asturias"
    AVILA = "avila"
    BADAJOZ = "badajoz"
    BALEARES = "baleares"
    BARCELONA = "barcelona"
    BILBAO = "bilbao"
    BURGOS = "burgos"
    CACERES = "caceres"
    CADIZ = "cadiz"
    CANTABRIA = "cantabria"
    CASTELLON = "castellon"
    CEUTA = "ceuta"
    CIUDAD_REAL = "ciudad-real"
    CORDOBA = "cordoba"
    LA_CORUNA = "la-coruna"
    CUENCA = "cuenca"
    GIJON = "gijon"
    GIRONA = "girona"
    GRANADA = "granada"
    GUADALAJARA = "guadalajara"
    GUIPUZCOA = "guipuzcoa"
    HUELVA = "huelva"
    HUESCA = "huesca"
    JAEN = "jaen"
    LEON = "leon"
    LLEIDA = "lleida"
    LOGRONO = "logrono"
    LUGO = "lugo"
    MADRID = "madrid"
    MALAGA = "malaga"
    MELILLA = "melilla"
    MURCIA = "murcia"
    NAVARRA = "navarra"
    OURENSE = "ourense"
    OVIEDO = "oviedo"
    PALENCIA = "palencia"
    PALMA_DE_MALLORCA = "palma-de-mallorca"
    LAS_PALMAS = "las-palmas"
    PAMPLONA = "pamplona"
    PONTEVEDRA = "pontevedra"
    LA_RIOJA = "la-rioja"
    SALAMANCA = "salamanca"
    SAN_SEBASTIAN = "san-sebastian"
    SANTANDER = "santander"
    SEGOVIA = "segovia"
    SEVILLA = "sevilla"
    SORIA = "soria"
    TARRAGONA = "tarragona"
    TENERIFE = "tenerife"
    TERUEL = "teruel"
    TOLEDO = "toledo"
    VALENCIA = "valencia"
    VALLADOLID = "valladolid"
    VITORIA = "vitoria"
    VIZCAYA = "vizcaya"
    ZAMORA = "zamora"
    ZARAGOZA = "zaragoza"


class Scope(Enum):
    NATIONAL = "national"
    REGIONAL = "regional"
    LOCAL = "local"
