name: Job - Lint and test

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Check black
        run: poetry run black --check ${{ inputs.project }}

      - name: Check ruff
        run: poetry run ruff check ${{ inputs.project }}

      - name: Check mypy
        run: poetry run mypy --ignore-missing-imports ${{ inputs.project }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest ${{ inputs.project }}
